### PR TITLE
Connect to unix socket

### PR DESCRIPTION
**Pull request by r-stu31**
Please review and merge the connect_to_unix_socket branch. It adds support for connecting to memcached using a unix socket.

The user must use a full pathname (must begin with a slash character: '/') in place of the "host:port" pair argument to Dalli::Client.new method for connecting to a unix socket.

### CODE REVIEW

**Comment by dfens** [comment]
@r-stu31 UNIX sockets were supported in previous versions of Dalli, but support was dropped with 2.x with premeditation

**Comment by r-stu31** [comment]
@dfens Thanks for the info. Could you please share a link to the discussion? I'd like to know the exact reasons, why a feature like this gets in the developers way.

**Comment by dfens** [comment]
@r-stu31 you can still use 1.1.5. some discussion was there https://github.com/mperham/dalli/issues/273 , if you want to force this topic my advise would be to discuss it with @mperham

**Comment by mperham** [comment]
I don't maintain Dalli; you are welcome to reopen the discussion with Peter.

**Comment by r-stu31** [comment]
@petergoldstein Hi, I'd like to reopen the discussion about a support for unix sockets in Dalli with you, as was suggested by @mperham.

Do you also maintain the idea that Dalli should not support unix sockets ``Because it was a support hassle. People didn't understand that sockets are limited to localhost.'' [#273, @mperham]? Thanks.

**Comment by petergoldstein** [comment]
@r-stu31 I'm happy to reopen the discussion.  I think @mperham's point about support is well-taken a a general guideline for features, but at the same time I'm not sure whether I agree that this particular feature shouldn't be supported by Dalli.  

Some pros in my mind:

1. Dalli is a driver for memcached, and it seems natural for Dalli to support the network interfaces that memcached supports
2. It is not feasible for a developer to extend Dalli to provide this support - it's too fundamental to the library

Some cons:

1. Minimal demand from the userbase - the 2.x branch has been out for a long time, and there hasn't been much clamor for this feature that I'm aware of.
2. As @mperham notes, there's a user complexity burden here - I'd want any PR including this functionality to include suitable documentation that would be clear to a novice user.

I'm in the middle of a few other things at the moment, but I'll give this a more detailed look this weekend and follow up then.

**Comment by petergoldstein** [comment]
So on balance, I'm inclined to re-add this functionality.  Before I do, I'd like to see some minor improvement in the documentation.  Currently the updated doc reads

For connecting to a unix socket, use a full pathname (must begin with a slash character: '/') in place of the "host:port" pair.

I'd prefer something more along the lines of:

Dalli also supports the ability to connect to Memcached on localhost through a UNIX socket.  To use this functionality, use a full pathname (beginning with a slash character '/') in place of the the "host:port" pair in the server configuration.

@r-stu31 Can you update the docs and squash to a single commit?  Thanks.

**Comment by r-stu31** [comment]
@petergoldstein Please clarify: do you want me to squash all the commits to a single commit (i.e. also squash the commit ```Don't accept "[]" as a hostname. Use grouping without capturing in the regexp where suitable. Add test.``` to the commit ```Add support for connecting to memcached using a unix socket ...```) or do you want me to squash only the minor improvement in the documentation to the commit ```Add support for connecting to memcached using a unix socket ...```? Thanks.

**Comment by petergoldstein** [comment]
@r-stu31 Just squash everything to a single commit.

**Comment by r-stu31** [comment]
@petergoldstein Done.

**Pull request merged**
